spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
        routeToLocalService: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://67.207.94.64:8762/eureka/

home-service:
  ribbon:
    eureka.enabled: true
    ServerListRefreshInterval: 100